### ISSUE TITLE
Doesn't seem to work on mobile

### ISSUE THREAD

**Issue by shannonjensen** [fac-12/KanyeKaraoke#28]
My mobile emulator showing this picture:
![image](https://user-images.githubusercontent.com/11382877/32653616-64316c30-c600-11e7-8bcb-b3fb732b551d.png)
and my actual mobile showing this (plus search not seeming to work strangely)
![image](https://user-images.githubusercontent.com/11382877/32653689-a01b7100-c600-11e7-9809-9323af78a397.png)

**Comment by Gbaja** [comment]
I think if you adjust the rem on the h1 and adjust the width of the tweet pic, that ought to fix it. Everything else seem to be responsive
